// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0CogJ-3LZK_NbxA3b471jX3ZVrxVAxuI',
    appId: '1:431657274502:web:15a0381cbd2729433bd507',
    messagingSenderId: '431657274502',
    projectId: 'sport-sync-pro',
    authDomain: 'sport-sync-pro.firebaseapp.com',
    databaseURL: 'https://sport-sync-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sport-sync-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc6GkGLSVNtpFVSEg_W7fqpgNlKU6ZnGA',
    appId: '1:431657274502:android:9685e24706842d763bd507',
    messagingSenderId: '431657274502',
    projectId: 'sport-sync-pro',
    databaseURL: 'https://sport-sync-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sport-sync-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEuiryJ_E43spwoZu0Qq9356FTleFXcUc',
    appId: '1:431657274502:ios:2f7b0d1a51cd6c7d3bd507',
    messagingSenderId: '431657274502',
    projectId: 'sport-sync-pro',
    databaseURL: 'https://sport-sync-pro-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sport-sync-pro.appspot.com',
    iosClientId: '431657274502-5hi8j4hrod651c4u4j002st2pf04fs8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportSyncProFlutter',
  );
}
